# - ansible.posix.
- name: Set vm.max_map_count to 262144 in /etc/sysctl.conf
  sysctl:
    name: vm.max_map_count
    value: '262144'
    state: present
# # - ansible.posix.
- name: Set fs.file-max to 65536 in /etc/sysctl.conf
  sysctl:
    name: fs.file-max
    value: '65536'
    state: present