---
- name: restart elasticsearch
  systemd: 
    daemon_reload: yes
    name: elasticsearch
    state: restarted
    enabled: yes


- name: restart kibana
  systemd:
    name: kibana
    state: restarted
    enabled: yes

- name: restart logstash
  systemd:
    name: logstash
    state: restarted
    enabled: yes

- name: restart filebeat
  systemd:
    name: filebeat
    state: restarted
    enabled: yes