# ansible_user                 : root
# ansible_ssh_pass             : p@ssw0rd

#####

ansible_user                 : worker
# ansible_ssh_pass             : qw
ansible_become_pass          : qw
# enviroment                   : STAGING
# peremennaya                  : peremennaya
