# ansible_user                 : root
# ansible_ssh_pass             : p@ssw0rd

#####

ansible_user                 : worker
ansible_ssh_pass             : asd
ansible_become_pass          : asd
# enviroment                   : STAGING
# peremennaya                  : peremennaya
