- name: Add app port to firewalld
  firewalld:
    service: "{{ item }}"
    permanent: yes
    state: enabled
  loop: "{{ firewall_services }}"
  notify: Restart firewalld



  #   port: "{{ item }}/tcp"
  #   permanent: yes
  #   state: enabled
  #   # state: disabled
  # loop: "{{ firewall_port }}"
  # notify: Restart firewalld

