---
version: "7.x"

### ES
es_http_port: 9200
cluster_init_master_nodes:  "192.168.0.210"
discovery_seed_hosts: 
  - "192.168.0.201"
  - "192.168.0.202"
  - "192.168.0.210"

sysd_config_file: "/etc/systemd/system/elasticsearch.service.d/override.conf"
es_cfg_dest_yml: "/etc/elasticsearch/elasticsearch.yml"
es_data_path: "/var/lib/elasticsearch"
es_logs_path: "/var/log/elasticsearch"


cluster_name: "my_cluster"
node_roles: 

### Kibana
install_kibana:
kibana_server_bind : "0.0.0.0"
ki_cfg_dest_yml: "/etc/kibana/kibana.yml"


### Log


### filebeat
filebeat_inputs:
  - type: log
    paths:
      - "/var/log/nginx/*.log"