---
# - name: RedHat - add Elasticsearch repo
#   template:
#     src: 'elasticsearch.repo'
#     dest: '/etc/yum.repos.d/elasticsearch.repo'

- name: RedHat - Elasticsearch repository
  yum_repository:
    name: elasticsearch
    description: "Elasticsearch repository for {{ version }} packages"
    baseurl: "{{ es_baseurl }}"
    gpgkey: "{{ es_gpgkey }}"
    gpgcheck: yes