---
- name: Config Control Host
  hosts: ctrl_host
  vars_files:
    - vars/hosts/ctrl_host.yml
    # - vars/jenkins.yml
    # - vars/java.yml
  roles:
    #     #### Users and ssh-keys
    # - create_users_and_groups
    # - ssh_create
    # - ssh_manipulate
    # - install_creds

    - es_reverse
    - install_icinga2
    - install_nginx
    - firewall

- name: Config workers
  hosts: workers
  vars_files:
    - vars/hosts/workers.yml
    # - vars/java.yml
  roles:
#     ###### Users and ssh-keys
#     - create_users_and_groups
#     - install_creds
    
    - install_nginx
    - firewall

# - name: Config db
#   hosts: db
#   vars_files:
#     - vars/hosts/db.yml
#   roles:
#     - resolv