---
- name: Config Control Host
  hosts: ctrl_host
  vars_files:
    - vars/hosts/ctrl_host.yml
  roles:
    #     #### Users and ssh-keys
    # - create_users_and_groups
    # - ssh_create
    # - ssh_manipulate
    # - install_creds

    - install_es
    # - install_icinga2
    - install_nginx
    - firewall

- name: Config workers
  hosts: workers
  vars_files:
    - vars/hosts/workers.yml
  roles:

    - swapoff
    - install_es
    - install_nginx
    - firewall